sudo: required

services:
  - docker

before_install:
  - docker build -t frontend_app -f Dockerfile.dev .

script:
  - docker run frontend_app npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "test-docker-travisci"
  env: "TestDockerTravisci-env"
  bucket_name: "elasticbeanstalk-us-east-1-542043849288"
  bucket_path: "test-docker-travisci"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
